

---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gitops-meta-repo
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
  namespace: fleet-local
spec:
  branch: main
  correctDrift:
    enabled: true
  clientSecretName: gitops-git-auth
  paths:
  
    - cluster-gitops/datacenters/aws/us-east/clusters/cluster-1/cluster
      - cluster-gitops/rancher-cluster/rancher
  repo: git@github.com:andrew-morris-rgs/rancher-dev-env.git
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester