---
apiVersion: v1
kind: Secret
metadata:
  labels:
    harvesterhci.io/cloud-init-template: harvester
  name: rancher-cloud-init
  namespace: default
type: Opaque
data:
  networkdata: ""
  userdata: CiNjbG91ZC1jb25maWcgCnBhY2thZ2VfdXBkYXRlOiB0cnVlCnBhY2thZ2VfdXBncmFkZTogdHJ1ZQp1c2VyczoKLSBkZWZhdWx0Ci0gbmFtZTogYWRtaW4KICBzdWRvOiBbJ0FMTD0oQUxMKSBOT1BBU1NXRDpBTEwnXQogIHNoZWxsOiAvYmluL2Jhc2gKICBwYXNzd2Q6ICR5JGo5VCRIaEc3czVHSWtleWJzVTNFMlpWdzgvJHdGcGtFMGFYeUxtYS5tZTFTaHpUTjBWU2diTmZHZ0JXa2hxVC5CSGIwSDcKICBsb2NrX3Bhc3N3ZDogZmFsc2UKcGFja2FnZXM6Ci0gZ2l0Ci0gYW5zaWJsZS1jb3JlCnJ1bmNtZDoKLSBhbnNpYmxlLXB1bGwgLVUgaHR0cHM6Ly9naXRodWIuY29tL3JhbmNoZXJmZWRlcmFsL3JrZTItYW5zaWJsZS5naXQgLWkgL2V0Yy9hbnNpYmxlL2ludmVudG9yeS9ob3N0cy55bWwgL2V0Yy9hbnNpYmxlL3BsYXlib29rcy9ya2UyLWluc3RhbGwtbG9jYWwueW1sCndyaXRlX2ZpbGVzOgotIHBhdGg6IC9ldGMvYW5zaWJsZS9hbnNpYmxlLmNmZwogIGNvbnRlbnQ6IHwKICAgIFtkZWZhdWx0c10KICAgIHJvbGVzX3BhdGggPSAvZXRjL2Fuc2libGUvcm9sZXMKICAgIHBsYXlib29rX2RpciA9IC9ldGMvYW5zaWJsZS9wbGF5Ym9va3MKLSBwYXRoOiAvZXRjL2Fuc2libGUvcGxheWJvb2tzL3JrZTItaW5zdGFsbC1sb2NhbC55bWwKICBjb250ZW50OiB8CiAgICAtLS0KICAgIC0gbmFtZTogSW5zdGFsbCBSS0UyIFNlcnZlcgogICAgICBob3N0czoKICAgICAgLSBsb2NhbGhvc3QKICAgICAgcm9sZXM6CiAgICAgIC0gcm9sZTogcmtlMgotIHBhdGg6IC9ldGMvYW5zaWJsZS9pbnZlbnRvcnkvaG9zdHMueW1sCiAgY29udGVudDogfAogICAgLS0tCiAgICBya2UyX2NsdXN0ZXI6CiAgICAgIGNoaWxkcmVuOgogICAgICAgIHJrZTJfc2VydmVyczoKICAgICAgICAgIGhvc3RzOgogICAgICAgICAgICBsb2NhbGhvc3Q6CiAgICAgICAgICAgICAgcmtlMl9pbnN0YWxsX3ZlcnNpb246IHYxLjMyLjktcmtlMnIxCiAgICAgICAgICAgICAgcmtlMl9yZWdpc3RyeV9jb25maWdfZmlsZV9wYXRoOiAvZXRjL3JhbmNoZXIvcmtlMi9yZWdpc3RyaWVzLnlhbWwKLSBwYXRoOiAvZXRjL3JhbmNoZXIvcmtlMi9yZWdpc3RyaWVzLnlhbWwKICBjb250ZW50OiB8CiAgICBtaXJyb3JzOgogICAgICB0cnVlOgogICAgICAgIGVuZHBvaW50OgogICAgICAgICAgLSBodHRwczovL3RydWUvdjIKICAgIGNvbmZpZ3M6CiAgICAgIHRydWU6Ci0gcGF0aDogL3Zhci9saWIvcmFuY2hlci9ya2UyL3NlcnZlci9tYW5pZmVzdHMvcG9zdC1kZXBsb3ktbWFuaWZlc3RzL2NlcnQtbWFuYWdlci55YW1sCiAgY29udGVudDogfAogICAgLS0tCiAgICBhcGlWZXJzaW9uOiBoZWxtLmNhdHRsZS5pby92MQogICAga2luZDogSGVsbUNoYXJ0CiAgICBtZXRhZGF0YToKICAgICAgICBuYW1lOiBjZXJ0LW1hbmFnZXIKICAgICAgICBuYW1lc3BhY2U6IGt1YmUtc3lzdGVtCiAgICBzcGVjOgogICAgICAgIGNoYXJ0OiBjZXJ0LW1hbmFnZXIKICAgICAgICByZXBvOiBodHRwczovL2NoYXJ0cy5qZXRzdGFjay5pbwogICAgICAgIHRhcmdldE5hbWVzcGFjZTogY2VydC1tYW5hZ2VyCiAgICAgICAgY3JlYXRlTmFtZXNwYWNlOiB0cnVlCiAgICAgICAgdmVyc2lvbjogMS4xOS4xCiAgICAgICAgdmFsdWVzQ29udGVudDogfC0KICAgICAgICAgICMgSGVsbSBjaGFydCB2YWx1ZXMgd2hpY2ggbWFrZSBjZXJ0LW1hbmFnZXIgY29tcGx5IHdpdGggQ0lTLCBCU0kgYW5kIE5TQQogICAgICAgICAgIyBzZWN1cml0eSBiZW5jaG1hcmtzIGFuZCBvdGhlciBiZXN0IHByYWN0aWNlcyBmb3IgZGVwbG95aW5nIGNlcnQtbWFuYWdlciBpbgogICAgICAgICAgIyBwcm9kdWN0aW9uLgogICAgICAgICAgY3JkczoKICAgICAgICAgICAgZW5hYmxlZDogdHJ1ZQoKICAgICAgICAgIGdsb2JhbDoKICAgICAgICAgICAgIHByaW9yaXR5Q2xhc3NOYW1lOiBzeXN0ZW0tY2x1c3Rlci1jcml0aWNhbAoKICAgICAgICAgIHJlcGxpY2FDb3VudDogMgogICAgICAgICAgcG9kRGlzcnVwdGlvbkJ1ZGdldDoKICAgICAgICAgICAgZW5hYmxlZDogdHJ1ZQogICAgICAgICAgICBtaW5BdmFpbGFibGU6IDEKICAgICAgICAgIGF1dG9tb3VudFNlcnZpY2VBY2NvdW50VG9rZW46IGZhbHNlCiAgICAgICAgICBzZXJ2aWNlQWNjb3VudDoKICAgICAgICAgICAgYXV0b21vdW50U2VydmljZUFjY291bnRUb2tlbjogZmFsc2UKICAgICAgICAgIHZvbHVtZXM6CiAgICAgICAgICAtIG5hbWU6IHNlcnZpY2VhY2NvdW50LXRva2VuCiAgICAgICAgICAgIHByb2plY3RlZDoKICAgICAgICAgICAgICBkZWZhdWx0TW9kZTogMDQ0NAogICAgICAgICAgICAgIHNvdXJjZXM6CiAgICAgICAgICAgICAgLSBzZXJ2aWNlQWNjb3VudFRva2VuOgogICAgICAgICAgICAgICAgICBleHBpcmF0aW9uU2Vjb25kczogMzYwNwogICAgICAgICAgICAgICAgICBwYXRoOiB0b2tlbgogICAgICAgICAgICAgIC0gY29uZmlnTWFwOgogICAgICAgICAgICAgICAgICBuYW1lOiBrdWJlLXJvb3QtY2EuY3J0CiAgICAgICAgICAgICAgICAgIGl0ZW1zOgogICAgICAgICAgICAgICAgICAtIGtleTogY2EuY3J0CiAgICAgICAgICAgICAgICAgICAgcGF0aDogY2EuY3J0CiAgICAgICAgICAgICAgLSBkb3dud2FyZEFQSToKICAgICAgICAgICAgICAgICAgaXRlbXM6CiAgICAgICAgICAgICAgICAgIC0gcGF0aDogbmFtZXNwYWNlCiAgICAgICAgICAgICAgICAgICAgZmllbGRSZWY6CiAgICAgICAgICAgICAgICAgICAgICBhcGlWZXJzaW9uOiB2MQogICAgICAgICAgICAgICAgICAgICAgZmllbGRQYXRoOiBtZXRhZGF0YS5uYW1lc3BhY2UKICAgICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAgIC0gbW91bnRQYXRoOiAvdmFyL3J1bi9zZWNyZXRzL2t1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQKICAgICAgICAgICAgbmFtZTogc2VydmljZWFjY291bnQtdG9rZW4KICAgICAgICAgICAgcmVhZE9ubHk6IHRydWUKCiAgICAgICAgICB3ZWJob29rOgogICAgICAgICAgICByZXBsaWNhQ291bnQ6IDMKICAgICAgICAgICAgcG9kRGlzcnVwdGlvbkJ1ZGdldDoKICAgICAgICAgICAgICBlbmFibGVkOiB0cnVlCiAgICAgICAgICAgICAgbWluQXZhaWxhYmxlOiAxCiAgICAgICAgICAgIGF1dG9tb3VudFNlcnZpY2VBY2NvdW50VG9rZW46IHRydWUgIyMgRklYTUUgaHR0cHM6Ly9jZXJ0LW1hbmFnZXIuaW8vZG9jcy9pbnN0YWxsYXRpb24vYmVzdC1wcmFjdGljZS8gcmVjb21tZW5kcyB0aGlzIGJlIHNldCBmYWxzZSBidXQgdGhhdCBmYWlscwogICAgICAgICAgICBzZXJ2aWNlQWNjb3VudDoKICAgICAgICAgICAgICBhdXRvbW91bnRTZXJ2aWNlQWNjb3VudFRva2VuOiB0cnVlICMjIEZJWE1FIGh0dHBzOi8vY2VydC1tYW5hZ2VyLmlvL2RvY3MvaW5zdGFsbGF0aW9uL2Jlc3QtcHJhY3RpY2UvIHJlY29tbWVuZHMgdGhpcyBiZSBzZXQgZmFsc2UgYnV0IHRoYXQgZmFpbHMKICAgICAgICAgICAgdm9sdW1lczoKICAgICAgICAgICAgLSBuYW1lOiBzZXJ2aWNlYWNjb3VudC10b2tlbgogICAgICAgICAgICAgIHByb2plY3RlZDoKICAgICAgICAgICAgICAgIGRlZmF1bHRNb2RlOiAwNDQ0CiAgICAgICAgICAgICAgICBzb3VyY2VzOgogICAgICAgICAgICAgICAgLSBzZXJ2aWNlQWNjb3VudFRva2VuOgogICAgICAgICAgICAgICAgICAgIGV4cGlyYXRpb25TZWNvbmRzOiAzNjA3CiAgICAgICAgICAgICAgICAgICAgcGF0aDogdG9rZW4KICAgICAgICAgICAgICAgIC0gY29uZmlnTWFwOgogICAgICAgICAgICAgICAgICAgIG5hbWU6IGt1YmUtcm9vdC1jYS5jcnQKICAgICAgICAgICAgICAgICAgICBpdGVtczoKICAgICAgICAgICAgICAgICAgICAtIGtleTogY2EuY3J0CiAgICAgICAgICAgICAgICAgICAgICBwYXRoOiBjYS5jcnQKICAgICAgICAgICAgICAgIC0gZG93bndhcmRBUEk6CiAgICAgICAgICAgICAgICAgICAgaXRlbXM6CiAgICAgICAgICAgICAgICAgICAgLSBwYXRoOiBuYW1lc3BhY2UKICAgICAgICAgICAgICAgICAgICAgIGZpZWxkUmVmOgogICAgICAgICAgICAgICAgICAgICAgICBhcGlWZXJzaW9uOiB2MQogICAgICAgICAgICAgICAgICAgICAgICBmaWVsZFBhdGg6IG1ldGFkYXRhLm5hbWVzcGFjZQogICAgICAgICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAgICAgICAtIG1vdW50UGF0aDogL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50CiAgICAgICAgICAgICAgICBuYW1lOiBzZXJ2aWNlYWNjb3VudC10b2tlbgogICAgICAgICAgICAgICAgcmVhZE9ubHk6IHRydWUKICAgICAgICAgIGNhaW5qZWN0b3I6CiAgICAgICAgICAgIGV4dHJhQXJnczoKICAgICAgICAgICAgLSAtLW5hbWVzcGFjZT1jZXJ0LW1hbmFnZXIKICAgICAgICAgICAgLSAtLWVuYWJsZS1jZXJ0aWZpY2F0ZXMtZGF0YS1zb3VyY2U9ZmFsc2UKICAgICAgICAgICAgcmVwbGljYUNvdW50OiAyCiAgICAgICAgICAgIHBvZERpc3J1cHRpb25CdWRnZXQ6CiAgICAgICAgICAgICAgZW5hYmxlZDogdHJ1ZQogICAgICAgICAgICAgIG1pbkF2YWlsYWJsZTogMQogICAgICAgICAgICBhdXRvbW91bnRTZXJ2aWNlQWNjb3VudFRva2VuOiBmYWxzZQogICAgICAgICAgICBzZXJ2aWNlQWNjb3VudDoKICAgICAgICAgICAgICBhdXRvbW91bnRTZXJ2aWNlQWNjb3VudFRva2VuOiBmYWxzZQogICAgICAgICAgICB2b2x1bWVzOgogICAgICAgICAgICAtIG5hbWU6IHNlcnZpY2VhY2NvdW50LXRva2VuCiAgICAgICAgICAgICAgcHJvamVjdGVkOgogICAgICAgICAgICAgICAgZGVmYXVsdE1vZGU6IDA0NDQKICAgICAgICAgICAgICAgIHNvdXJjZXM6CiAgICAgICAgICAgICAgICAtIHNlcnZpY2VBY2NvdW50VG9rZW46CiAgICAgICAgICAgICAgICAgICAgZXhwaXJhdGlvblNlY29uZHM6IDM2MDcKICAgICAgICAgICAgICAgICAgICBwYXRoOiB0b2tlbgogICAgICAgICAgICAgICAgLSBjb25maWdNYXA6CiAgICAgICAgICAgICAgICAgICAgbmFtZToga3ViZS1yb290LWNhLmNydAogICAgICAgICAgICAgICAgICAgIGl0ZW1zOgogICAgICAgICAgICAgICAgICAgIC0ga2V5OiBjYS5jcnQKICAgICAgICAgICAgICAgICAgICAgIHBhdGg6IGNhLmNydAogICAgICAgICAgICAgICAgLSBkb3dud2FyZEFQSToKICAgICAgICAgICAgICAgICAgICBpdGVtczoKICAgICAgICAgICAgICAgICAgICAtIHBhdGg6IG5hbWVzcGFjZQogICAgICAgICAgICAgICAgICAgICAgZmllbGRSZWY6CiAgICAgICAgICAgICAgICAgICAgICAgIGFwaVZlcnNpb246IHYxCiAgICAgICAgICAgICAgICAgICAgICAgIGZpZWxkUGF0aDogbWV0YWRhdGEubmFtZXNwYWNlCiAgICAgICAgICAgIHZvbHVtZU1vdW50czoKICAgICAgICAgICAgLSBtb3VudFBhdGg6IC92YXIvcnVuL3NlY3JldHMva3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudAogICAgICAgICAgICAgIG5hbWU6IHNlcnZpY2VhY2NvdW50LXRva2VuCiAgICAgICAgICAgICAgcmVhZE9ubHk6IHRydWUKCiAgICAgICAgICBzdGFydHVwYXBpY2hlY2s6CiAgICAgICAgICAgIGF1dG9tb3VudFNlcnZpY2VBY2NvdW50VG9rZW46IGZhbHNlCiAgICAgICAgICAgIHNlcnZpY2VBY2NvdW50OgogICAgICAgICAgICAgIGF1dG9tb3VudFNlcnZpY2VBY2NvdW50VG9rZW46IGZhbHNlCiAgICAgICAgICAgIHZvbHVtZXM6CiAgICAgICAgICAgIC0gbmFtZTogc2VydmljZWFjY291bnQtdG9rZW4KICAgICAgICAgICAgICBwcm9qZWN0ZWQ6CiAgICAgICAgICAgICAgICBkZWZhdWx0TW9kZTogMDQ0NAogICAgICAgICAgICAgICAgc291cmNlczoKICAgICAgICAgICAgICAgIC0gc2VydmljZUFjY291bnRUb2tlbjoKICAgICAgICAgICAgICAgICAgICBleHBpcmF0aW9uU2Vjb25kczogMzYwNwogICAgICAgICAgICAgICAgICAgIHBhdGg6IHRva2VuCiAgICAgICAgICAgICAgICAtIGNvbmZpZ01hcDoKICAgICAgICAgICAgICAgICAgICBuYW1lOiBrdWJlLXJvb3QtY2EuY3J0CiAgICAgICAgICAgICAgICAgICAgaXRlbXM6CiAgICAgICAgICAgICAgICAgICAgLSBrZXk6IGNhLmNydAogICAgICAgICAgICAgICAgICAgICAgcGF0aDogY2EuY3J0CiAgICAgICAgICAgICAgICAtIGRvd253YXJkQVBJOgogICAgICAgICAgICAgICAgICAgIGl0ZW1zOgogICAgICAgICAgICAgICAgICAgIC0gcGF0aDogbmFtZXNwYWNlCiAgICAgICAgICAgICAgICAgICAgICBmaWVsZFJlZjoKICAgICAgICAgICAgICAgICAgICAgICAgYXBpVmVyc2lvbjogdjEKICAgICAgICAgICAgICAgICAgICAgICAgZmllbGRQYXRoOiBtZXRhZGF0YS5uYW1lc3BhY2UKICAgICAgICAgICAgdm9sdW1lTW91bnRzOgogICAgICAgICAgICAtIG1vdW50UGF0aDogL3Zhci9ydW4vc2VjcmV0cy9rdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50CiAgICAgICAgICAgICAgbmFtZTogc2VydmljZWFjY291bnQtdG9rZW4KICAgICAgICAgICAgICByZWFkT25seTogdHJ1ZQogICAgICAgICAgCi0gcGF0aDogL3Zhci9saWIvcmFuY2hlci9ya2UyL3NlcnZlci9tYW5pZmVzdHMvcG9zdC1kZXBsb3ktbWFuaWZlc3RzL3JhbmNoZXIueWFtbAogIGNvbnRlbnQ6IHwKICAgIC0tLQogICAgYXBpVmVyc2lvbjogaGVsbS5jYXR0bGUuaW8vdjEKICAgIGtpbmQ6IEhlbG1DaGFydAogICAgbWV0YWRhdGE6CiAgICAgICAgbmFtZTogcmFuY2hlcgogICAgICAgIG5hbWVzcGFjZToga3ViZS1zeXN0ZW0KICAgIHNwZWM6CiAgICAgICAgY2hhcnQ6IHJhbmNoZXIKICAgICAgICByZXBvOiBodHRwczovL3JlbGVhc2VzLnJhbmNoZXIuY29tL3NlcnZlci1jaGFydHMvc3RhYmxlCiAgICAgICAgdGFyZ2V0TmFtZXNwYWNlOiBjYXR0bGUtc3lzdGVtCiAgICAgICAgY3JlYXRlTmFtZXNwYWNlOiB0cnVlCiAgICAgICAgdmVyc2lvbjogdjIuMTIuMgogICAgICAgIHZhbHVlc0NvbnRlbnQ6IHwtCiAgICAgICAgICBob3N0bmFtZTogcmFuY2hlci0xOTIuMTY4LjEuMTUyLnNzbGlwLmlvCiAgICAgICAgICBib290c3RyYXBQYXNzd29yZDogMTIzNCFAIyRxZXdyUVdFUgogICAgICAgICAgcmVwbGljYXM6IDMKICAgICAgICAgICMjIFNUSUcgQ29uZmlncwogICAgICAgICAgYXVkaXRMb2c6CiAgICAgICAgICAgIGxldmVsOiAyCgoKCgoKCgo=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-disk-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi 
  storageClassName: longhorn-image-h2sj5
  volumeMode: Block
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rancher-192.168.1.152.sslip.io
  namespace: default
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: rancher-192.168.1.152.sslip.io
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network.harvesterhci.io/mgmt
                    operator: In
                    values:
                      - 'true'
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              macAddress: 06:34:8c:19:d4:d1
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 8Gi
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
          requests:
            cpu: 250m
            memory: 10922Mi
      evictionStrategy: LiveMigrateIfPossible
      hostname: rancher
      networks:
        - multus:
            networkName: default/rancher-mgmt
          name: default
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: rancher-disk-0
        - cloudInitNoCloud:
            networkDataSecretRef:
              name: rancher-cloud-init
            secretRef:
              name: rancher-cloud-init
          name: cloudinitdisk
